ci:
  autoupdate_schedule: quarterly
  autoupdate_branch: 'trunk-patch'
  autofix_prs: false

# these exclusions must be synced with ruff-format agove and the file ruff.toml.
exclude: |
  (?x)(
    ^hoomd/_hoomd.py|
    ^hoomd/version_config.py|
    ^hoomd/md/_md.py|
    ^hoomd/hpmc/_hpmc.py|
    ^hoomd/mpcd/_mpcd.py|
    ^hoomd/extern/|
    ^sphinx-doc/tutorial/
    ^hoomd/metal/
  )

repos:
- repo: local
  hooks:
  - id: check-maintainer
    name: Check for maintainer comments
    description: 'Enforce that `maintainer` comments are removed.'
    entry: '(# Maintainer:|\/\/ Maintainer:)'
    language: pygrep
    types_or: [python, c, c++, cuda, inc]
- repo: local
  hooks:
  - id: generate_toctree
    name: Generate Sphinx toctree
    language: python
    entry: python3 sphinx-doc/generate-toctree.py
    pass_filenames: false
    always_run: true
    additional_dependencies:
     - numpy==2.1.0
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v5.0.0'
  hooks:
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: check-json
  - id: check-yaml
  - id: check-case-conflict
  - id: mixed-line-ending
- repo: https://github.com/glotzerlab/fix-license-header
  rev: v0.4.1
  hooks:
  - id: fix-license-header
    name: Fix license headers
    exclude: |
      (?x)(
          ^hoomd/extern/|
          ^sphinx-doc/tutorial/|
          ^sphinx-doc/howto/
          )
    types_or: [python, c, c++, cuda, inc]
    args:
    - --license-file=LICENSE
    - --add=Part of HOOMD-blue, released under the BSD 3-Clause License.
    - --keep-before=#!
    - --keep-after=.. include
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.8.6'
  hooks:
  - id: ruff-format
    types_or: [python]
  - id: ruff
    types_or: [python]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.6
  hooks:
  - id: clang-format
    types_or: [c, c++, cuda, inc]
    exclude: |
      (?x)(
        ^CMake/|
        ^hoomd/extern/
      )
