name: GitHub Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
    - "trunk-*"
    tags:
      - "v*"

  workflow_dispatch:


env:
  name: hoomd

defaults:
  run:
    shell: bash


jobs:
  release:
    name: Build release tarball
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        submodules: true
        path: code

    - name: Install tools
      run: sudo apt-get install pcregrep pandoc

    - name: Determine last tag via git describe
      if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
      run: echo "tag=$(git describe --abbrev=0)" >> $GITHUB_ENV
      working-directory: code

    # git describe does not return the current tag in tag pushes on GitHub Actions, use GITHUB_REF instead
    - name: Determine tag from GITHUB_REF
      if:  startsWith(github.ref, 'refs/tags/v')
      run: echo "tag=$(echo ${GITHUB_REF} | sed  -e 's/refs\/tags\///g')" >> $GITHUB_ENV

    - name: Write version change log
      run: .github/workflows/make-changelog-md.sh  ${tag:1} | tee ${GITHUB_WORKSPACE}/changelog.md
      working-directory: code

    - name: Copy source
      run: cp -R code ${name}-${tag:1}

    - name: Remove .git
      run: rm -rf ${name}-${tag:1}/.git && ls -laR ${name}-${tag:1}

    - name: Tar source
      run: tar -cvzf ${name}-${tag:1}.tar.gz ${name}-${tag:1}

    - name: Tar source
      run: tar -cvJf ${name}-${tag:1}.tar.xz ${name}-${tag:1}

    - name: Upload release files
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: release
        path: |
          *.tar.gz
          changelog.md

  publish:
    name: Publish [GitHub]
    needs: [release]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: release

    - name: Create release
      uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: "*.tar.*"
        body_path: changelog.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
