name: Update conda lockfiles

on:
  schedule:
    - cron: '9 12 1-7 3,6,2,12 4'

  workflow_dispatch:

jobs:
  update:
    uses: glotzerlab/workflows/.github/workflows/update-conda-lockfiles.yaml@a36a97114c60241b26217ce92abbb64621ac67c7 # 0.6.0
    secrets: inherit
    with:
      branch: trunk-patch
